In [6]:
#check numpy version
#numpy = numerical python
#numpy is used to deal with arrays, array is 50 times faster than list but it consistss same data types
#Arrays : 1D(single list), 2D(matrix form : shape should be mantained) 
import numpy as np
#np.__versio

In [ ]:
#convert list into array
lst = [1,2,3,4,5]
ar1 = np.array(lst)    #.array():converts list into array
ar1
print(ar1)
#print(type(ar1))     #array is in n-dimensions


[1 2 3 4 5]


' \n\n'

In [17]:
#if different data type
lst = [1,2,3,'4',5]    
ar1 = np.array(lst)   
ar1

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [21]:
#range mei array banani hai
import numpy as np
ar2 = np.arange(1,20)   #isse float nhi ata
ar2



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [24]:
#by using np.linspace : fixed number of points 
import numpy as np
ar3 = np.linspace(1,20,5)   #isse 1-20 ke bich 5 woh values milengi jinme equal gap hai
ar3


array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [29]:
#array jisme sara elements 1 ya 0 ho
ar4 = np.ones(5)   #1 dalne e liye
ar4

ar5 = np.zeros(5)  #o dalne ke liye har element ke liye
ar5

array([0., 0., 0., 0., 0.])

In [32]:
#2 d array with 0's or 1's
ar6 = np.zeros((2,3))  #for 2D : ((rows,columns))
ar6

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
#arr.reshape: for conversion of 1D array to 2D array-----idhr arr. mtlb array ka naam
ar7 = np.arange(1,13)         #rows * cols == total elements
ar7_2D = ar7.reshape(2,6)     #rows columns ke jagah agar -1 likh de toh by default woh 1Darray de dega orserf single value p error dega
ar7_2D

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
#Creating array from random numbers
ar8 = np.random.randint(1,100,10) 
ar8 
ar9 = np.random.random(10)  #ye randint jaisa hai bs float mein values dega, bs ye 1 hi attribute dega
ar9


array([61, 21, 95, 45, 25, 95, 40,  5, 40, 22], dtype=int32)

In [49]:
ar10= np.arange(20,80)
ar10_2D = ar10.reshape(6,10)
ar10_2D

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [57]:
ar11 = np.random.randint(20,80,60)
ar11_2D = ar11.reshape(6,10)
ar11_2D

array([[72, 60, 26, 67, 56, 41, 62, 20, 36, 65],
       [52, 20, 64, 48, 68, 31, 72, 74, 69, 76],
       [69, 28, 32, 54, 78, 42, 52, 21, 48, 48],
       [61, 49, 25, 49, 56, 79, 21, 45, 40, 70],
       [34, 62, 30, 66, 50, 58, 23, 60, 38, 79],
       [36, 57, 56, 56, 26, 53, 51, 41, 21, 41]], dtype=int32)

In [59]:
'''
arr.shape :
arr.datatype :
arr.size :
arr.ndin :

'''

'\narr.shape :\narr.datatype :\narr.size :\narr.ndin :\n\n'

In [64]:
#conversion of 2D array into 1
ar12 = np.random.randint(20,80,60)
ar12_2D = ar11.reshape(6,10)
ar12_2D.ravel()
#arr11_2D.flatten()                 #.ravel(), .flatten() both are same

array([29, 45, 55, 52, 76, 47, 43, 29, 22, 34, 34, 62, 49, 28, 29, 45, 52,
       42, 32, 22, 60, 60, 51, 79, 20, 45, 32, 25, 65, 20, 77, 65, 46, 52,
       73, 72, 34, 69, 71, 69, 35, 77, 59, 64, 74, 29, 70, 35, 71, 76, 34,
       65, 55, 38, 24, 50, 54, 78, 21, 52], dtype=int32)

In [ ]:
#for transpose for array : use .T.shape()
ar13 = np.random.randint(20,80,60)
ar13_2D = ar13.reshape(6,10)
ar13_t = ar13_2D.T.shape
ar13_t

(10, 6)

In [74]:
#Indexing and Slicing

#for 1D: same like list
lst2 = [1,2,3,4,5,6,7,8,9]
ar14
ar14[5] = 15
ar14
ar14[2:6]    #for slicing use [a:b],where a and b are range
            


array([ 3,  4,  5, 15])

In [89]:
#Indexing and Slicing

#for 2D array
# (row start point:rowend:rowskip,colstart:colend:colskip)
ar14 = np.random.randint(20,80,60)
ar14_2D = ar13.reshape(6,10)
print(ar14_2D[1:3,2:3][0][0])

#print(ar14_2D)



100


In [ ]:
#Reverse of Rows
ar15 = np.random.randint(20,80,60)
ar15_2D = ar15.reshape(6,10)
revers_ar15_2D = ar15_2D[::-1,::-1] # reverse of both rows and columns
revers_ar15_2D = ar15_2D[::-1]      #reverse of rows
revers_ar15_2D = ar15_2D[:,::-1]    #reverse of columns
print(revers_ar15_2D)

[[53 24 77 32 65 63 48 55 25 47]
 [70 22 38 70 58 77 66 49 31 54]
 [71 73 47 29 68 23 39 51 55 31]
 [70 47 75 50 71 25 34 65 52 49]
 [29 30 40 61 43 39 25 73 32 53]
 [55 27 66 58 60 62 28 41 50 39]]


In [103]:
#3 array: [2,2,3]-----2 row or 3 columns ki matrix 2 block mein hai mtlb aisi 2 matrix hai
a = np.random.randint(1,70,50).reshape(2,5,5)
print(a)

[[[67 34 55  8 52]
  [68 37 44  6 22]
  [ 3  1 54 32 37]
  [21  4 15 20 55]
  [24 41 49  9 51]]

 [[40 15 29 30 62]
  [58 31 61 56 42]
  [20 26 28 14 63]
  [ 1 13 69 22 44]
  [62 55 16 10  9]]]


In [112]:
#slicing in 3Daray  synatx:
# [table start:table end:table skip,row start:row end:row skip,col start:col end:col skip]
b = np.random.randint(1,70,50).reshape(5,2,5)
print(b[0:2,0:1,0:2])



[[[ 4  9]]

 [[34 35]]]


In [114]:
'''
array mtlb yaha pe array ka naam
np.max(array) : maximum number or array
np.min(array)
np.sum(array)
np.mean(array)
np.median(array)
np.std(array)
array.sort : ascending order mei sort kr dega, descending ke liye kuvh nhi(ascending krke indexing reverse krdo
array,argsort : sort krta hai pr index ki value deta hai

'''

'\narray mtlb yaha pe array ka naam\nnp.max(array) : maximum number or array\nnp.min(array)\nnp.sum(array)\nnp.mean(array)\nnp.median(array)\nnp.std(array)\narray.sort : ascending order mei sort kr dega, descending ke liye kuvh nhi(ascending krke indexing reverse krdo\narray,argsort : sort krta hai pr index ki value deta hai\n\n'

In [ ]:
#sort krke reverse : descending order
arc = np.arange(20,80)
arc_2D = arc.reshape(6,10)
arc_2D.sort()
rev_a = arc_2D[::-1,::-1]
print(rev_a)

[[79 78 77 76 75 74 73 72 71 70]
 [69 68 67 66 65 64 63 62 61 60]
 [59 58 57 56 55 54 53 52 51 50]
 [49 48 47 46 45 44 43 42 41 40]
 [39 38 37 36 35 34 33 32 31 30]
 [29 28 27 26 25 24 23 22 21 20]]
